---
# Playbook pour récupérer le mot de passe administrateur initial de Jenkins
- name: Get Jenkins initial admin password
  hosts: jenkins
  become: yes
  
  tasks:
    - name: Read initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false
      
    - name: Display Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"
